### ISSUE TITLE
Error code 500 from listDataBySensor request

### ISSUE THREAD

**Issue by esdrasjnr** [CESARBR/knot-cloud-storage#12]
I have an application that makes requests to storage, and sometimes I got error code 500 as response. In most times it goes successfully, but I get this error casually.

I have open this issue here to help track that bug.

**Comment by netoax** [comment]
@EsdrasJunior can you add a step-by-step to reproduce this issue, please? And if possible logs so that we can investigate it.

**Comment by esdrasjnr** [comment]
> @EsdrasJunior can you add a step-by-step to reproduce this issue, please? And if possible logs so that we can investigate it.

@joaoaneto the problem occurs randomly, I just call the `listDataBySensor` method and it throw an error like the image below:

![Screenshot from 2019-10-22 10-30-19](https://user-images.githubusercontent.com/26424330/67291344-c999c080-f4b7-11e9-97dc-ebbf4b34d746.png)

**Comment by lcbm** [comment]
@joaoaneto @esdrasjnr @Igoraamc I'm assuming this is fixed :joy: 
Can we close this, please?
